### ISSUE TITLE
Feature wish ;)

### ISSUE THREAD

**Issue by chrstnwhlrt** [webRTC-io/webRTC.io#1]
Maybe you could extend your demo to work like apprtc (apprtc.appspot.com), manage
different sessions with random numbers and allow within a session more than two users.

**Comment by benbrittain** [comment]
this would be really easy. I'll totally add it in later this week.

**Comment by dennismartensson** [comment]
This is now implemented and are on the demo site, You can get a randome room by clicking on the button or you can create your own by adding # and the room name you want. 

http://multiwebrtc.nodejitsu.com/#<roomname>
