### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by flo-sch** [webRTC-io/webRTC.io#22]
Hi there,

I'm using webrtc-io with nodejs and it seems to work well, I mean I can join a room when I know which one to join.

I would to know if it's possible to notify the server (and by this way, the other online users of any app) when someone open a channel / room, or when someone join one.

I was looking for a documentation on the callbacks and events available on both the client and server sides, but I did not find a lot of things.
Does a complete book / documentation on these API exists anywhere ?
If not, I would to create one, but I need to know which methods are available, so if someone could send me that?
Thanks in advance !

**Comment by emlazzarin** [comment]
Second that... documentation leaves a lot to be desired. For example, you can disable video with the `{"video": false, "audio": true}` option, but there is no documentation on how to handle that in a document.
