### ISSUE TITLE
Doesn't work with new webkitRTCPeerConnection

### ISSUE THREAD

**Issue by rileydutton** [webRTC-io/webRTC.io#9]
Chrome 23 is out and it has deprecated the old webkitPeerConnection00 object. Even if you try to allow support for webkitRTCPeerConnection, it fails on:

var pc = rtc.peerConnections[id] = new PeerConnection(rtc.SERVER, function(candidate, moreToFollow) {

with error "Not an object."

**Comment by rileydutton** [comment]
Sorry, this should have been posted on the client, not the server.

**Comment by coderaiser** [comment]
added suport of chrome Version 25.0.1323.0 canary https://github.com/webRTC/webrtc.io-client/pull/12

**Comment by atulpundhir** [comment]
It still doesn't work on chrome 23. Gives types error.

**Comment by michielbdejong** [comment]
from https://codereview.chromium.org/10957035/patch/9001/3003 it looks like the interface changed and you should now do something like:

```
var peerConn = new webkitRTCPeerConnection({iceServers:[{url:'stun:stun.l.google.com:19302'}]}, onSignal);
```

instead of the old way which was:

```
var peerConn = new PeerConnection('STUN stun.l.google.com:19302', onSignal);
```

HTH

**Comment by michielbdejong** [comment]
actually the onSignal callback is also gone, see the createPeerConnection function in:

```
view-source:https://apprtc.appspot.com/
```

**Comment by dennismartensson** [comment]
If you have the time and skill please submit a pull request.

Thank you!
